### ISSUE TITLE
run generated Terraform code

### ISSUE THREAD

**Issue by kevgo** [Originate/exosphere#310]
> When deploying an Exosphere application
I want that Exosphere runs the Terraform code for me
So that I don't need to have Terraform and other ops tools on my machine.

- running "exo perform-deploy" executes the Terraform code
- Terraform runs in a Docker image

#### todo
- [ ] @chrizkim, @Bowbaq: I heard rumors you want to run several different Terraform scripts here, one for infrastructure and one for the services. Please define these steps here.

**Comment by kevgo** [comment]
blocked on input from @chrizkim and @Bowbaq

**Comment by Bowbaq** [comment]
Without context, it's hard to tell what you're trying to achieve here. At face value, this is not useful. 

- It's vastly easier to install terraform (simply download a binary) than it is to install exosphere.
- Wrapping terraform in exosphere simply adds a layer that we'll need to maintain, which adds complexity and reduces flexibility.
- Generating terraform code doesn't seem ideal, why not leverage modules? Additionally, I've yet to see a project that didn't require some amount of custom terraform code. Does this tool allow manually written templates?
- Doing everything in one step negates one of the major feature of terraform, planning, which lets the operator inspect the changes before they are applied
- Terraform extracts credentials for providers from the environment / various files on the host system. Running it containerized will mean locating & mounting all of these.

To the extent that we want to have developers that are ignorant of terraform perform infrastructure changes, I think limiting the possible blast radius is an important design concern. This can be achieved by isolating each part of the infrastructure in its own state file, and linking them together via the remote state data source.

Additional question:
- How does this handle different terraform versions?
- How does this handle secrets?
- How does this handle deploying to different environments (dev / qa / prod ...)?
- How does this handle deploying a specific version of a service?
- How does this handle bootstrapping the AWS (or other) account to be ready for use by terraform?

**Comment by hugobho** [comment]
I'll answer the questions that I can:

> Wrapping terraform in exosphere simply adds a layer that we'll need to maintain, which adds complexity and reduces flexibility.

The main pain point we try to do away with is all the boilerplate Terraform that's repeated between applications. These are the modules that we want to provide built into Exosphere. There are two main "types" Terraform scripts that we're dealing with: 1) a bunch of modules, already written and built into exosphere, that almost every application will need. Applications will use these as building blocks. 2) An application specific Terraform file built off said packaged modules and generated by reading application config. This file contains modules specific to the application and is checked into git. 

I do agree we should try to keep the deployment steps as close to the Terraform commands as possible, and not conflate all of them into on giant "deploy" command. But then it does seem like we might as well be using Terraform directly and not build this extra layer of indirection on top of it. Idk, open to suggestions here.

> Generating terraform code doesn't seem ideal, why not leverage modules? 

We are leveraging modules to create the basic infrastructure: vpcs, subnets, security groups, dns, cluster, service skeletons, etc. These scripts aren't generated and come packaged with Exosphere. The file that is generated will contain app-specific resources that utilize those packaged modules. This includes basic application config, which services to run on the main cluster, locked Terraform version and remote state config.

> Additionally, I've yet to see a project that didn't require some amount of custom terraform code. Does this tool allow manually written templates?

Yes, we allow custom Terraform modules though we have to think about how to make that integration as seamless as possible. For instance ExoCom requires its own cluster/service modules that not every application will need. These are listed under a `custom/` directory within the overall "packaged" Terraform modules. Only applications that use ExoCom will require that module - an application that uses Nats might require an analogous one. This does limit custom modules to the ones that we've already written, so it doesn't really answer your question. We have to figure out a better system for integrating user-written Terraform.

> Doing everything in one step negates one of the major feature of terraform, planning, which lets the operator inspect the changes before they are applied

We are planning on extracting deployment into two separate steps: planning and applying.

> Terraform extracts credentials for providers from the environment / various files on the host system. Running it containerized will mean locating & mounting all of these.

Yes, although we'll have to mount the whole application to read its config data anyways. What are the argument against doing this? The idea is that everything we need to find will be inside the application directory, and we'll document where the user should put their environment and variable files. 

> How does this handle different terraform versions? 

A `terraform` block in every root level script will lock the version used.

> How does this handle secrets?

I've been storing all secrets in a `terraform.tfvars` file and `.gitignore`-ing that, though I'm open to suggestions. Any secret field that would otherwise be checked into git is then a variable.

> How does this handle bootstrapping the AWS (or other) account to be ready for use by terraform?

So far `terraform init` has been sufficient - it reads the `backend` block within the `terraform` object:
```
terraform {
  required_version = "= 0.9.9"

  backend "s3" {
    bucket     = "space-tweet-terraform"
    key        = "dev/terraform.tfstate"
    region     = "us-west-2"
    lock_table = "TerraformLocks"
  }
}
```
