### ISSUE TITLE
"exo clean" should remove existing Docker containers for the app

### ISSUE THREAD

**Issue by kevgo** [Originate/exosphere#320]
> When there are running Docker containers that break "exo run"
I want to be able to stop and remove them cleanly using "exo clean"
So that I can start my application normally without having to google how to remove Docker containers manually.

#### Rules:
- running "exo clean" stops and removes all Docker containers that are listed in application.yml 
- running Docker containers are stopped by running `docker stop <container names>`
- stopped Docker containers are removed by running `docker rm <container names>`

#### Notes:
This fixes this error:
```
exo-run  Creating web ... error
               exo-run  

               exo-run  ERROR: for web  Cannot create container for service web: Conflict. The container name "/web" is already in use by container    "f266b77ba98a3212d1ad727c1659195136c6c4968ad92c0961d4afe20087b06a". 
                               You have to remove (or rename) that container to be able to reuse that name.
```

**Comment by hugoesthere** [comment]
I think the issue you're running into is pre-existing Docker _containers_. The feature specs should look more like this:
> When there are running Docker containers that break "exo run"
I want to be able to stop and remove them cleanly using "exo clean"
So that I can start my application normally without having to google how to remove Docker containers manually.

#### Rules:
- running "exo clean" stops and removes all Docker containers that are listed in application.yml 
- Running Docker containers are stopped by running `docker stop <container names>`
- Stopped Docker containers are removed by running `docker rm <container names>`

**Comment by kevgo** [comment]
Excellent! I have adopted your proposal in the ticket description.

**Comment by hugoesthere** [comment]
Currently blocked on https://github.com/Originate/exosphere/issues/491
