### ISSUE TITLE
port exo-test to go

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#368]
* Tests should be run in the same docker image as used for `exo run` (will most likely share the same setup code)
* Add support for multiple test commands (this is in order to support extra setup needed since the docker image may only install the production dependencies and not the test dependencies)
  * Note: it may be worthwhile down the line to have them define a separate dockerfile for tests

@hugobho @kevgo Please review criteria and then we can start work

**Comment by hugoesthere** [comment]
This looks good to me. The only thing I'm unsure about is how connecting services to dependency containers (such as mongo) will work. When services and dependencies are part of the same [network](https://docs.docker.com/compose/networking/) they can connect easily just by using container names. This is something we get for free with `docker-compose` - it runs all services in the same network. It might look different with exo test since we're not using `docker compose`, or it might not be a problem at all. If it is, it should be an easy fix anyways. I think it's just a flag or something that we pass.

**Comment by kevgo** [comment]
Maybe boot up the service plus it's dependencies using a custom-built Docker compose file?

**Comment by hugoesthere** [comment]
Which ever is easier. We do have code for building docker-compose files and running docker-compose processes we might be able to reuse. Or if it's easier to boot up independent processes and link them manually then we could do that. Might be worth doing a manual test before we start implementation. Just boot up a mongo container and a dummy service and see if the service can connect.

**Comment by charlierudolph** [comment]
closed in f3275f704769ca4b33cd8d21a81da0dae0c1aa49
