### ISSUE TITLE
exo deploy: automate exocom env vars

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#497]
When deploying an application with exocom, the env vars each service needs should be auto-populated so they don't need to be listed in the `service.yml`.

See https://github.com/Originate/space-tweet/pull/34/files#r135900724

**Comment by charlierudolph** [comment]
@hugobho I'd like to get this fixed for EDX. So to me there are a couple updates that we need to make. Couple questions:

* Where is the exocom host name created? (or how to mirror what the name terraform gives it?)
* Can I unit test this? Since we had sme unit tests for addinng the service routes as an env variable, I am guessing yes but am unsure.

**Comment by hugoesthere** [comment]
> Where is the exocom host name created?

That's fixed in the `.tf` modules, it's created across multiple `.tf` files but the only dynamic part of `exocom.app-name.local` is `app-name`. Everything else is hard-coded so we can easily mirror the name as long as we know the application name.
> Can I unit test this?

I think we can. Just test the function that generates environment variables, and if Exocom is a listed app dependency then check that those fields are there.
