### ISSUE TITLE
exo deploy: read public aws config from app.yml

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#529]
Read public AWS config from application.yml including:
- region
- account id
- ssl centificate arn

**Comment by hugoesthere** [comment]
I think region should actually be passed in as a flag, so that you can deploy to multiple regions. We can default to `us-west-2` if the user doesn't pass one in. 

Let's just provide fixed region support for this alpha, but I've created a ticket for this: https://github.com/Originate/exosphere/issues/540
