### ISSUE TITLE
exo deploy: update ecs-cluster security group

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#554]
Allow all inbound traffic from within that security group. We added the RDS instance to the ecs-cluster security group in order to allow a service to connect to it. The next deploy removed this rule.

If there is a different place we should add this then that works too.

@alexdavid @hugobho

**Comment by hugoesthere** [comment]
I think we restricted all inbound traffic into the ecs-cluster to tighten security. Probably the best option might be to create an RDS instance using Terraform and pass that security group into the list of allowed sgs for the ecs-cluster, but that kind of sounds like this ticket: https://github.com/Originate/exosphere/issues/505

**Comment by charlierudolph** [comment]
Correct.. But what about in the short-term and to support externally setup resources? What security group would we need to add the resource to in order for a service to access it?

**Comment by hugoesthere** [comment]
Hm that brings up a good question - how do we mix Terraform managed and user managed resources? In the short term if we can implement this two part deploy of main infra then services (https://github.com/Originate/exosphere/issues/553) then in future deploys the ecs-cluster sg shouldn't be changed because we're only modifying services. But that seems like a brittle solution, and now the Terraform state files don't reflect Terraform managed resources on aws. @alexdavid any ideas?

**Comment by alexdavid** [comment]
I'd still want non-exosphere managed resources to still be written in terraform, maybe a `custom.tf` file or something where we inject shared resource ids like security groups and subnet ids

**Comment by charlierudolph** [comment]
Closing as this was resolved with RDS support
