### ISSUE TITLE
exo deploy: bug in initial deploy

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#655]
@alexdavid says this is due to a bug in our initial deploy where we are missing a depends on

<img width="428" alt="screen shot 2017-10-06 at 6 15 46 pm" src="https://user-images.githubusercontent.com/1676758/31303439-801447fa-aac2-11e7-85ad-6bdc280b893e.png">

**Comment by hugoesthere** [comment]
So it seems like Terraform does not currently support `depends_on` for modules: https://github.com/hashicorp/terraform/issues/1178. The workaround mentioned does not apply in this case unless we separate creation of the alb and service. Or we can just create the lb within the service module instead of reusing an alb module like we do right now (this is what Titan is doing). I look at stack's code: they create a lb outside of the service module and they don't use `depends_on`, but it's an elb that they create so I don't know if that makes a difference.

@alexdavid any suggestions?
