### ISSUE TITLE
exo test: pull / build phases

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#735]
Currently when testing any service, it pulls/builds for the entire test file.

When testing a service, we pull/build only the service (does that auto pull/build its deps?)

When testing a application we could optimize to pull/build everything at the beginning and not while testing each service

@hugobho saw this when trying out the latest with EDX

**Comment by hugoesthere** [comment]
> Currently when testing any service, it pulls/builds for the entire test file.

You're saying before or after the release of `0.29.0`? After `0.29.0` it should only be pulling/building per service if we're testing from the service level

> When testing a service, we pull/build only the service (does that auto pull/build its deps?)

Yes, it pulls/builds any service listed in `depends_on`.

> When testing a application we could optimize to pull/build everything at the beginning and not while testing each service

I'm not sure this provides much of an advantage. When you're testing a whole application, the total runtime will be the same no matter when we build everything. Also, if the user wants to interrupt tests when one fails, it makes a lot more sense to build before each service instead of all at once at the beginning where they risk waiting for all services to build only to have a test fail early on.

**Comment by charlierudolph** [comment]
After `0.29.0` it does a pull and build on the entire `test.yml` file without passing in specific images to build / pull.

I was thinking of the optimization for the shared deps. Don't think it would say that much time anyway though

**Comment by hugoesthere** [comment]
Ah yes, we don't specify service name for the build/pull step. I'll open a PR for that now
